/**
 * Excel Custom Ribbon Creator - Automatically Generated Icons Map
 * Generated At: 05/31/2026 16:51:09
 */

const ICONS_MAP = {
    "Project Green":  [
                          "Document_Dark.svg",
                          "Document_Gray.svg",
                          "Document_Light.svg",
                          "Megaphone_Loud_Dark.svg",
                          "Megaphone_Loud_Gray.svg",
                          "Megaphone_Loud_Light.svg",
                          "Text_Bullet_List_Dark.svg",
                          "Text_Bullet_List_Gray.svg",
                          "Text_Bullet_List_Light.svg",
                          "Text_Bullet_List_Square_Dark.svg",
                          "Text_Bullet_List_Square_Gray.svg",
                          "Text_Bullet_List_Square_Light.svg"
                      ],
    "Microsoft Blue":  {
                           "48x48 Grey \u0026 Blue Icon":  [
                                                               "Apps List Detail.svg",
                                                               "Apps.svg",
                                                               "Arrow Circle Left.svg",
                                                               "Arrow Circle Right.svg",
                                                               "Arrow Clockwise.svg",
                                                               "Arrow Down.svg",
                                                               "Arrow Download.svg",
                                                               "Arrow Sync.svg",
                                                               "Arrow Upload.svg",
                                                               "Attach.svg",
                                                               "Book Contacts.svg",
                                                               "Bot.svg",
                                                               "Building Cloud.svg",
                                                               "Building Multiple.svg",
                                                               "Building People_Blue_Gray.svg",
                                                               "Building Retail.svg",
                                                               "Building.svg",
                                                               "Calculator.svg",
                                                               "Calendar Month.svg",
                                                               "Call.svg",
                                                               "Camera.svg",
                                                               "Cart.svg",
                                                               "Certificate.svg",
                                                               "Chart Multiple.svg",
                                                               "Chat Multiple.svg",
                                                               "Chat.svg",
                                                               "Check.svg",
                                                               "Checkmark Circle.svg",
                                                               "Chevron Circle.svg",
                                                               "Clipboard Task List.svg",
                                                               "Clock Alarm.svg",
                                                               "Clock.svg",
                                                               "Cloud Add.svg",
                                                               "Cloud Arrow Down.svg",
                                                               "Cloud Arrow Up.svg",
                                                               "Cloud Beaker.svg",
                                                               "Cloud Cube.svg",
                                                               "Cloud Database.svg",
                                                               "Cloud Desktop.svg",
                                                               "Cloud.svg",
                                                               "Code.svg",
                                                               "Column Arrow Right.svg",
                                                               "Comment Multiple.svg",
                                                               "Comment.svg",
                                                               "Data Area.svg",
                                                               "Data Bar Vertical.svg",
                                                               "Data Pie.svg",
                                                               "Data Trending (1).svg",
                                                               "Data Trending.svg",
                                                               "Data Usage.svg",
                                                               "Database.svg",
                                                               "Deploy.svg",
                                                               "Desktop Arrow Down.svg",
                                                               "Desktop Tower.svg",
                                                               "Dismiss Circle.svg",
                                                               "Document Bullet List Multiple.svg",
                                                               "Document Bullet List.svg",
                                                               "Document Key.svg",
                                                               "Document Lock.svg",
                                                               "Document Multiple.svg",
                                                               "Document One Page.svg",
                                                               "Document Text.svg",
                                                               "Document.svg",
                                                               "Edit.svg",
                                                               "Filmstrip Play.svg",
                                                               "Fingerprint.svg",
                                                               "Flag.svg",
                                                               "Folder Multiple.svg",
                                                               "Folder Open Vertical.svg",
                                                               "Folder Open.svg",
                                                               "Folder People.svg",
                                                               "Globe.svg",
                                                               "Grid Circles.svg",
                                                               "Handshake.svg",
                                                               "Hat Graduation.svg",
                                                               "Headset.svg",
                                                               "Heart Pulse.svg",
                                                               "Heart.svg",
                                                               "Image.svg",
                                                               "Key.svg",
                                                               "Laptop.svg",
                                                               "Layer Diagonal.svg",
                                                               "Lightbulb Checkmark.svg",
                                                               "Lightbulb.svg",
                                                               "Lock Closed.svg",
                                                               "Lock Shield.svg",
                                                               "Mail Alert.svg",
                                                               "Mail Attach.svg",
                                                               "Mail Error.svg",
                                                               "Mail Read.svg",
                                                               "Mail.svg",
                                                               "Map.svg",
                                                               "Megaphone Loud.svg",
                                                               "Merge.svg",
                                                               "Notebook.svg",
                                                               "Number Circle 1.svg",
                                                               "Number Circle 2.svg",
                                                               "Number Circle 3.svg",
                                                               "Number Circle 4.svg",
                                                               "Organization Horizontal.svg",
                                                               "Organization.svg",
                                                               "Panel Left Header Key.svg",
                                                               "Panel Left Header.svg",
                                                               "Payment.svg",
                                                               "People Audience.svg",
                                                               "People Community.svg",
                                                               "People Settings.svg",
                                                               "People Team.svg",
                                                               "People.svg",
                                                               "Person Accounts.svg",
                                                               "Person Desktop.svg",
                                                               "Person Settings.svg",
                                                               "Person Square.svg",
                                                               "Person Wrench.svg",
                                                               "Person.svg",
                                                               "Phone Desktop.svg",
                                                               "Phone Laptop.svg",
                                                               "Phone Tablet.svg",
                                                               "Phone Update.svg",
                                                               "Phone.svg",
                                                               "Presenter.svg",
                                                               "Question Circle.svg",
                                                               "Radar.svg",
                                                               "Receipt.svg",
                                                               "Ribbon Star.svg",
                                                               "Ribbon.svg",
                                                               "Road Cone.svg",
                                                               "Script.svg",
                                                               "Search.svg",
                                                               "Select All.svg",
                                                               "Settings Cog Multiple.svg",
                                                               "Settings.svg",
                                                               "Shapes Three.svg",
                                                               "Share Screen Person Overlay.svg",
                                                               "Share Screen Person.svg",
                                                               "Share.svg",
                                                               "Shield Error.svg",
                                                               "Shifts Activity.svg",
                                                               "Shopping Bag.svg",
                                                               "Signature.svg",
                                                               "Slide Layout.svg",
                                                               "Tablet Laptop.svg",
                                                               "Tablet.svg",
                                                               "Tap.svg",
                                                               "Task List Square.svg",
                                                               "Text First Line.svg",
                                                               "Text Number List.svg",
                                                               "Toolbox.svg",
                                                               "Top Speed.svg",
                                                               "Video.svg",
                                                               "Wallet Credit Card.svg",
                                                               "Window Dev Edit.svg",
                                                               "Window Edit.svg",
                                                               "Window.svg",
                                                               "Wrench.svg"
                                                           ],
                           "48x48 Dark Blue Icon":  [
                                                        "Apps List Detail.svg",
                                                        "Apps.svg",
                                                        "Arrow Circle Left.svg",
                                                        "Arrow Circle Right.svg",
                                                        "Arrow Clockwise.svg",
                                                        "Arrow Down.svg",
                                                        "Arrow Download.svg",
                                                        "Arrow Sync.svg",
                                                        "Arrow Upload.svg",
                                                        "Attach.svg",
                                                        "Book Contacts.svg",
                                                        "Bot.svg",
                                                        "Building Cloud.svg",
                                                        "Building Multiple.svg",
                                                        "Building People_Blue_Dark.svg",
                                                        "Building Retail.svg",
                                                        "Building.svg",
                                                        "Calculator.svg",
                                                        "Calendar Month.svg",
                                                        "Call.svg",
                                                        "Camera.svg",
                                                        "Cart.svg",
                                                        "Certificate.svg",
                                                        "Chart Multiple.svg",
                                                        "Chat Multiple.svg",
                                                        "Chat.svg",
                                                        "Check.svg",
                                                        "Checkmark Circle.svg",
                                                        "Chevron Circle.svg",
                                                        "Clipboard Task List.svg",
                                                        "Clock Alarm.svg",
                                                        "Clock.svg",
                                                        "Cloud Add.svg",
                                                        "Cloud Arrow Down.svg",
                                                        "Cloud Arrow Up.svg",
                                                        "Cloud Beaker.svg",
                                                        "Cloud Cube.svg",
                                                        "Cloud Database.svg",
                                                        "Cloud Desktop.svg",
                                                        "Cloud.svg",
                                                        "Code.svg",
                                                        "Column Arrow Right.svg",
                                                        "Comment Multiple.svg",
                                                        "Comment.svg",
                                                        "Data Area.svg",
                                                        "Data Bar Vertical.svg",
                                                        "Data Pie.svg",
                                                        "Data Trending (1).svg",
                                                        "Data Trending.svg",
                                                        "Data Usage.svg",
                                                        "Database.svg",
                                                        "Deploy.svg",
                                                        "Desktop Arrow Down.svg",
                                                        "Desktop Tower.svg",
                                                        "Dismiss Circle.svg",
                                                        "Document Bullet List Multiple.svg",
                                                        "Document Bullet List.svg",
                                                        "Document Key.svg",
                                                        "Document Lock.svg",
                                                        "Document Multiple.svg",
                                                        "Document One Page.svg",
                                                        "Document Text.svg",
                                                        "Document.svg",
                                                        "Edit.svg",
                                                        "Filmstrip Play.svg",
                                                        "Fingerprint.svg",
                                                        "Flag.svg",
                                                        "Folder Multiple.svg",
                                                        "Folder Open Vertical.svg",
                                                        "Folder Open.svg",
                                                        "Folder People.svg",
                                                        "Globe.svg",
                                                        "Grid Circles.svg",
                                                        "Handshake.svg",
                                                        "Hat Graduation.svg",
                                                        "Headset.svg",
                                                        "Heart Pulse.svg",
                                                        "Heart.svg",
                                                        "Image.svg",
                                                        "Key.svg",
                                                        "Laptop.svg",
                                                        "Layer Diagonal.svg",
                                                        "Lightbulb Checkmark.svg",
                                                        "Lightbulb.svg",
                                                        "Lock Closed.svg",
                                                        "Lock Shield.svg",
                                                        "Mail Alert.svg",
                                                        "Mail Attach.svg",
                                                        "Mail Error.svg",
                                                        "Mail Read.svg",
                                                        "Mail.svg",
                                                        "Map.svg",
                                                        "Megaphone Loud.svg",
                                                        "Merge.svg",
                                                        "Notebook.svg",
                                                        "Number Circle 1.svg",
                                                        "Number Circle 2.svg",
                                                        "Number Circle 3.svg",
                                                        "Number Circle 4.svg",
                                                        "Organization Horizontal.svg",
                                                        "Organization.svg",
                                                        "Panel Left Header Key.svg",
                                                        "Panel Left Header.svg",
                                                        "Payment.svg",
                                                        "People Audience.svg",
                                                        "People Community.svg",
                                                        "People Settings.svg",
                                                        "People Team.svg",
                                                        "People.svg",
                                                        "Person Accounts.svg",
                                                        "Person Desktop.svg",
                                                        "Person Settings.svg",
                                                        "Person Square.svg",
                                                        "Person Wrench.svg",
                                                        "Person.svg",
                                                        "Phone Desktop.svg",
                                                        "Phone Laptop.svg",
                                                        "Phone Tablet.svg",
                                                        "Phone Update.svg",
                                                        "Phone.svg",
                                                        "Presenter.svg",
                                                        "Question Circle.svg",
                                                        "Radar.svg",
                                                        "Receipt.svg",
                                                        "Ribbon Star.svg",
                                                        "Ribbon.svg",
                                                        "Road Cone.svg",
                                                        "Script.svg",
                                                        "Search.svg",
                                                        "Select All.svg",
                                                        "Settings Cog Multiple.svg",
                                                        "Settings.svg",
                                                        "Shapes Three.svg",
                                                        "Share Screen Person Overlay.svg",
                                                        "Share Screen Person.svg",
                                                        "Share.svg",
                                                        "Shield Error.svg",
                                                        "Shifts Activity.svg",
                                                        "Shopping Bag.svg",
                                                        "Signature.svg",
                                                        "Slide Layout.svg",
                                                        "Tablet Laptop.svg",
                                                        "Tablet.svg",
                                                        "Tap.svg",
                                                        "Task List Square.svg",
                                                        "Text First Line.svg",
                                                        "Text Number List.svg",
                                                        "Toolbox.svg",
                                                        "Top Speed.svg",
                                                        "Video.svg",
                                                        "Wallet Credit Card.svg",
                                                        "Window Dev Edit.svg",
                                                        "Window Edit.svg",
                                                        "Window.svg",
                                                        "Wrench.svg"
                                                    ],
                           "48x48 Light Blue Icon":  [
                                                         "Apps List Detail.svg",
                                                         "Apps.svg",
                                                         "Arrow Circle Left.svg",
                                                         "Arrow Circle Right.svg",
                                                         "Arrow Clockwise.svg",
                                                         "Arrow Down.svg",
                                                         "Arrow Download.svg",
                                                         "Arrow Sync.svg",
                                                         "Arrow Upload.svg",
                                                         "Attach.svg",
                                                         "Book Contacts.svg",
                                                         "Bot.svg",
                                                         "Building Cloud.svg",
                                                         "Building Multiple.svg",
                                                         "Building People_Blue_Light.svg",
                                                         "Building Retail.svg",
                                                         "Building.svg",
                                                         "Calculator.svg",
                                                         "Calendar Month.svg",
                                                         "Call.svg",
                                                         "Camera.svg",
                                                         "Cart.svg",
                                                         "Certificate.svg",
                                                         "Chart Multiple.svg",
                                                         "Chat Multiple.svg",
                                                         "Chat.svg",
                                                         "Check.svg",
                                                         "Checkmark Circle.svg",
                                                         "Chevron Circle.svg",
                                                         "Clipboard Task List.svg",
                                                         "Clock Alarm.svg",
                                                         "Clock.svg",
                                                         "Cloud Add.svg",
                                                         "Cloud Arrow Down.svg",
                                                         "Cloud Arrow Up.svg",
                                                         "Cloud Beaker.svg",
                                                         "Cloud Cube.svg",
                                                         "Cloud Database.svg",
                                                         "Cloud Desktop.svg",
                                                         "Cloud.svg",
                                                         "Code.svg",
                                                         "Column Arrow Right.svg",
                                                         "Comment Multiple.svg",
                                                         "Comment.svg",
                                                         "Data Area.svg",
                                                         "Data Bar Vertical.svg",
                                                         "Data Pie.svg",
                                                         "Data Trending (1).svg",
                                                         "Data Trending.svg",
                                                         "Data Usage.svg",
                                                         "Database.svg",
                                                         "Deploy.svg",
                                                         "Desktop Arrow Down.svg",
                                                         "Desktop Tower.svg",
                                                         "Dismiss Circle.svg",
                                                         "Document Bullet List Multiple.svg",
                                                         "Document Bullet List.svg",
                                                         "Document Key.svg",
                                                         "Document Lock.svg",
                                                         "Document Multiple.svg",
                                                         "Document One Page.svg",
                                                         "Document Text.svg",
                                                         "Document.svg",
                                                         "Edit.svg",
                                                         "Filmstrip Play.svg",
                                                         "Fingerprint.svg",
                                                         "Flag.svg",
                                                         "Folder Multiple.svg",
                                                         "Folder Open Vertical.svg",
                                                         "Folder Open.svg",
                                                         "Folder People.svg",
                                                         "Globe.svg",
                                                         "Grid Circles.svg",
                                                         "Handshake.svg",
                                                         "Hat Graduation.svg",
                                                         "Headset.svg",
                                                         "Heart Pulse.svg",
                                                         "Heart.svg",
                                                         "Image.svg",
                                                         "Key.svg",
                                                         "Laptop.svg",
                                                         "Layer Diagonal.svg",
                                                         "Lightbulb Checkmark.svg",
                                                         "Lightbulb.svg",
                                                         "Lock Closed.svg",
                                                         "Lock Shield.svg",
                                                         "Mail Alert.svg",
                                                         "Mail Attach.svg",
                                                         "Mail Error.svg",
                                                         "Mail Read.svg",
                                                         "Mail.svg",
                                                         "Map.svg",
                                                         "Megaphone Loud.svg",
                                                         "Merge.svg",
                                                         "Notebook.svg",
                                                         "Number Circle 1.svg",
                                                         "Number Circle 2.svg",
                                                         "Number Circle 3.svg",
                                                         "Number Circle 4.svg",
                                                         "Organization Horizontal.svg",
                                                         "Organization.svg",
                                                         "Panel Left Header Key.svg",
                                                         "Panel Left Header.svg",
                                                         "Payment.svg",
                                                         "People Audience.svg",
                                                         "People Community.svg",
                                                         "People Settings.svg",
                                                         "People Team.svg",
                                                         "People.svg",
                                                         "Person Accounts.svg",
                                                         "Person Desktop.svg",
                                                         "Person Settings.svg",
                                                         "Person Square.svg",
                                                         "Person Wrench.svg",
                                                         "Person.svg",
                                                         "Phone Desktop.svg",
                                                         "Phone Laptop.svg",
                                                         "Phone Tablet.svg",
                                                         "Phone Update.svg",
                                                         "Phone.svg",
                                                         "Presenter.svg",
                                                         "Question Circle.svg",
                                                         "Radar.svg",
                                                         "Receipt.svg",
                                                         "Ribbon Star.svg",
                                                         "Ribbon.svg",
                                                         "Road Cone.svg",
                                                         "Script.svg",
                                                         "Search.svg",
                                                         "Select All.svg",
                                                         "Settings Cog Multiple.svg",
                                                         "Settings.svg",
                                                         "Shapes Three.svg",
                                                         "Share Screen Person Overlay.svg",
                                                         "Share Screen Person.svg",
                                                         "Share.svg",
                                                         "Shield Error.svg",
                                                         "Shifts Activity.svg",
                                                         "Shopping Bag.svg",
                                                         "Signature.svg",
                                                         "Slide Layout.svg",
                                                         "Tablet Laptop.svg",
                                                         "Tablet.svg",
                                                         "Tap.svg",
                                                         "Task List Square.svg",
                                                         "Text First Line.svg",
                                                         "Text Number List.svg",
                                                         "Toolbox.svg",
                                                         "Top Speed.svg",
                                                         "Video.svg",
                                                         "Wallet Credit Card.svg",
                                                         "Window Dev Edit.svg",
                                                         "Window Edit.svg",
                                                         "Window.svg",
                                                         "Wrench.svg"
                                                     ]
                       },
    "Teams Purple":  {
                         "48x48 Grey \u0026 Purple Icon":  [
                                                               "Apps List Detail.svg",
                                                               "Apps.svg",
                                                               "Arrow Circle Left.svg",
                                                               "Arrow Circle Right.svg",
                                                               "Arrow Clockwise.svg",
                                                               "Arrow Down.svg",
                                                               "Arrow Download.svg",
                                                               "Arrow Sync.svg",
                                                               "Arrow Upload.svg",
                                                               "Attach.svg",
                                                               "Book Contacts.svg",
                                                               "Bot.svg",
                                                               "Building Multiple.svg",
                                                               "Building People.svg",
                                                               "Building Retail.svg",
                                                               "Building.svg",
                                                               "Calculator.svg",
                                                               "Calendar Month.svg",
                                                               "Call.svg",
                                                               "Camera.svg",
                                                               "Cart.svg",
                                                               "Certificate.svg",
                                                               "Chart Multiple.svg",
                                                               "Chat Multiple.svg",
                                                               "Chat.svg",
                                                               "Check.svg",
                                                               "Checkmark Circle.svg",
                                                               "Chevron Circle.svg",
                                                               "Clipboard Task List.svg",
                                                               "Clock Alarm.svg",
                                                               "Clock.svg",
                                                               "Cloud Add.svg",
                                                               "Cloud Arrow Down.svg",
                                                               "Cloud Arrow Up.svg",
                                                               "Cloud Database.svg",
                                                               "Cloud Desktop.svg",
                                                               "Cloud.svg",
                                                               "Code.svg",
                                                               "Column Arrow Right.svg",
                                                               "Comment Multiple.svg",
                                                               "Comment.svg",
                                                               "Data Area.svg",
                                                               "Data Bar Vertical.svg",
                                                               "Data Pie.svg",
                                                               "Data Trending (2).svg",
                                                               "Data Trending.svg",
                                                               "Data Usage.svg",
                                                               "Database.svg",
                                                               "Desktop Arrow Down.svg",
                                                               "Desktop Tower.svg",
                                                               "Dismiss Circle.svg",
                                                               "Document Bullet List Multiple.svg",
                                                               "Document Bullet List.svg",
                                                               "Document Key.svg",
                                                               "Document Lock.svg",
                                                               "Document Multiple.svg",
                                                               "Document One Page.svg",
                                                               "Document Text.svg",
                                                               "Document.svg",
                                                               "Edit.svg",
                                                               "Filmstrip Play.svg",
                                                               "Fingerprint.svg",
                                                               "Flag.svg",
                                                               "Folder Multiple.svg",
                                                               "Folder Open Vertical.svg",
                                                               "Folder Open.svg",
                                                               "Folder People.svg",
                                                               "Globe.svg",
                                                               "Hat Graduation.svg",
                                                               "Headset.svg",
                                                               "Heart Pulse.svg",
                                                               "Heart.svg",
                                                               "Image.svg",
                                                               "Key.svg",
                                                               "Laptop.svg",
                                                               "Layer Diagonal.svg",
                                                               "Lightbulb Checkmark.svg",
                                                               "Lightbulb.svg",
                                                               "Lock Closed.svg",
                                                               "Lock Shield.svg",
                                                               "Mail Alert.svg",
                                                               "Mail Attach.svg",
                                                               "Mail Error.svg",
                                                               "Mail Read.svg",
                                                               "Mail.svg",
                                                               "Map.svg",
                                                               "Megaphone Loud.svg",
                                                               "Merge.svg",
                                                               "Notebook.svg",
                                                               "Number Circle 1.svg",
                                                               "Number Circle 2.svg",
                                                               "Number Circle 3.svg",
                                                               "Number Circle 4.svg",
                                                               "Organization Horizontal.svg",
                                                               "Organization.svg",
                                                               "Panel Left Header Key.svg",
                                                               "Payment.svg",
                                                               "People Audience.svg",
                                                               "People Settings.svg",
                                                               "People Team.svg",
                                                               "People.svg",
                                                               "Person Accounts.svg",
                                                               "Person Desktop.svg",
                                                               "Person Settings.svg",
                                                               "Person Square.svg",
                                                               "Person Wrench.svg",
                                                               "Person.svg",
                                                               "Phone Desktop.svg",
                                                               "Phone Laptop.svg",
                                                               "Phone Tablet.svg",
                                                               "Phone Update.svg",
                                                               "Phone.svg",
                                                               "Presenter.svg",
                                                               "Question Circle.svg",
                                                               "Radar.svg",
                                                               "Receipt.svg",
                                                               "Ribbon Star.svg",
                                                               "Ribbon.svg",
                                                               "Road Cone.svg",
                                                               "Script.svg",
                                                               "Search.svg",
                                                               "Select All.svg",
                                                               "Settings Cog Multiple.svg",
                                                               "Settings.svg",
                                                               "Share Screen Person Overlay.svg",
                                                               "Share Screen Person.svg",
                                                               "Share.svg",
                                                               "Shield Error.svg",
                                                               "Shifts Activity.svg",
                                                               "Shopping Bag.svg",
                                                               "Signature.svg",
                                                               "Slide Layout.svg",
                                                               "Tablet Laptop.svg",
                                                               "Tablet.svg",
                                                               "Tap.svg",
                                                               "Task List Square.svg",
                                                               "Text First Line.svg",
                                                               "Text Number List.svg",
                                                               "Toolbox.svg",
                                                               "Top Speed.svg",
                                                               "Video.svg",
                                                               "Wallet Credit Card.svg",
                                                               "Window Edit.svg",
                                                               "Window.svg",
                                                               "Wrench.svg"
                                                           ],
                         "48x48 Dark Purple Icon":  [
                                                        "Apps List Detail.svg",
                                                        "Apps.svg",
                                                        "Arrow Circle Left.svg",
                                                        "Arrow Circle Right.svg",
                                                        "Arrow Clockwise.svg",
                                                        "Arrow Down.svg",
                                                        "Arrow Download.svg",
                                                        "Arrow Sync.svg",
                                                        "Arrow Upload.svg",
                                                        "Attach.svg",
                                                        "Book Contacts.svg",
                                                        "Bot.svg",
                                                        "Building Multiple.svg",
                                                        "Building People.svg",
                                                        "Building Retail.svg",
                                                        "Building.svg",
                                                        "Calculator.svg",
                                                        "Calendar Month.svg",
                                                        "Call.svg",
                                                        "Camera.svg",
                                                        "Cart.svg",
                                                        "Certificate.svg",
                                                        "Chart Multiple.svg",
                                                        "Chat Multiple.svg",
                                                        "Chat.svg",
                                                        "Check.svg",
                                                        "Checkmark Circle.svg",
                                                        "Chevron Circle.svg",
                                                        "Clipboard Task List.svg",
                                                        "Clock Alarm.svg",
                                                        "Clock.svg",
                                                        "Cloud Add.svg",
                                                        "Cloud Arrow Down.svg",
                                                        "Cloud Arrow Up.svg",
                                                        "Cloud Database.svg",
                                                        "Cloud Desktop.svg",
                                                        "Cloud.svg",
                                                        "Code.svg",
                                                        "Column Arrow Right.svg",
                                                        "Comment Multiple.svg",
                                                        "Comment.svg",
                                                        "Data Area.svg",
                                                        "Data Bar Vertical.svg",
                                                        "Data Pie.svg",
                                                        "Data Trending (2).svg",
                                                        "Data Trending.svg",
                                                        "Data Usage.svg",
                                                        "Database.svg",
                                                        "Desktop Arrow Down.svg",
                                                        "Desktop Tower.svg",
                                                        "Dismiss Circle.svg",
                                                        "Document Bullet List Multiple.svg",
                                                        "Document Bullet List.svg",
                                                        "Document Key.svg",
                                                        "Document Lock.svg",
                                                        "Document Multiple.svg",
                                                        "Document One Page.svg",
                                                        "Document Text.svg",
                                                        "Document.svg",
                                                        "Edit.svg",
                                                        "Filmstrip Play.svg",
                                                        "Fingerprint.svg",
                                                        "Flag.svg",
                                                        "Folder Multiple.svg",
                                                        "Folder Open Vertical.svg",
                                                        "Folder Open.svg",
                                                        "Folder People.svg",
                                                        "Globe.svg",
                                                        "Hat Graduation.svg",
                                                        "Headset.svg",
                                                        "Heart Pulse.svg",
                                                        "Heart.svg",
                                                        "Image.svg",
                                                        "Key.svg",
                                                        "Laptop.svg",
                                                        "Layer Diagonal.svg",
                                                        "Lightbulb Checkmark.svg",
                                                        "Lightbulb.svg",
                                                        "Lock Closed.svg",
                                                        "Lock Shield.svg",
                                                        "Mail Alert.svg",
                                                        "Mail Attach.svg",
                                                        "Mail Error.svg",
                                                        "Mail Read.svg",
                                                        "Mail.svg",
                                                        "Map.svg",
                                                        "Megaphone Loud.svg",
                                                        "Merge.svg",
                                                        "Notebook.svg",
                                                        "Number Circle 1.svg",
                                                        "Number Circle 2.svg",
                                                        "Number Circle 3.svg",
                                                        "Number Circle 4.svg",
                                                        "Organization Horizontal.svg",
                                                        "Organization.svg",
                                                        "Panel Left Header Key.svg",
                                                        "Payment.svg",
                                                        "People Audience.svg",
                                                        "People Settings.svg",
                                                        "People Team.svg",
                                                        "People.svg",
                                                        "Person Accounts.svg",
                                                        "Person Desktop.svg",
                                                        "Person Settings.svg",
                                                        "Person Square.svg",
                                                        "Person Wrench.svg",
                                                        "Person.svg",
                                                        "Phone Desktop.svg",
                                                        "Phone Laptop.svg",
                                                        "Phone Tablet.svg",
                                                        "Phone Update.svg",
                                                        "Phone.svg",
                                                        "Presenter.svg",
                                                        "Question Circle.svg",
                                                        "Radar.svg",
                                                        "Receipt.svg",
                                                        "Ribbon Star.svg",
                                                        "Ribbon.svg",
                                                        "Road Cone.svg",
                                                        "Script.svg",
                                                        "Search.svg",
                                                        "Select All.svg",
                                                        "Settings Cog Multiple.svg",
                                                        "Settings.svg",
                                                        "Share Screen Person Overlay.svg",
                                                        "Share Screen Person.svg",
                                                        "Share.svg",
                                                        "Shield Error.svg",
                                                        "Shifts Activity.svg",
                                                        "Shopping Bag.svg",
                                                        "Signature.svg",
                                                        "Slide Layout.svg",
                                                        "Tablet Laptop.svg",
                                                        "Tablet.svg",
                                                        "Tap.svg",
                                                        "Task List Square.svg",
                                                        "Text First Line.svg",
                                                        "Text Number List.svg",
                                                        "Toolbox.svg",
                                                        "Top Speed.svg",
                                                        "Video.svg",
                                                        "Wallet Credit Card.svg",
                                                        "Window Edit.svg",
                                                        "Window.svg",
                                                        "Wrench.svg"
                                                    ],
                         "48x48 Light Purple Icon":  [
                                                         "Apps List Detail.svg",
                                                         "Apps.svg",
                                                         "Arrow Circle Left.svg",
                                                         "Arrow Circle Right.svg",
                                                         "Arrow Clockwise.svg",
                                                         "Arrow Down.svg",
                                                         "Arrow Download.svg",
                                                         "Arrow Sync.svg",
                                                         "Arrow Upload.svg",
                                                         "Attach.svg",
                                                         "Book Contacts.svg",
                                                         "Bot.svg",
                                                         "Building Multiple.svg",
                                                         "Building People.svg",
                                                         "Building Retail.svg",
                                                         "Building.svg",
                                                         "Calculator.svg",
                                                         "Calendar Month.svg",
                                                         "Call.svg",
                                                         "Camera.svg",
                                                         "Cart.svg",
                                                         "Certificate.svg",
                                                         "Chart Multiple.svg",
                                                         "Chat Multiple.svg",
                                                         "Chat.svg",
                                                         "Check.svg",
                                                         "Checkmark Circle.svg",
                                                         "Chevron Circle.svg",
                                                         "Clipboard Task List.svg",
                                                         "Clock Alarm.svg",
                                                         "Clock.svg",
                                                         "Cloud Add.svg",
                                                         "Cloud Arrow Down.svg",
                                                         "Cloud Arrow Up.svg",
                                                         "Cloud Database.svg",
                                                         "Cloud Desktop.svg",
                                                         "Cloud.svg",
                                                         "Code.svg",
                                                         "Column Arrow Right.svg",
                                                         "Comment Multiple.svg",
                                                         "Comment.svg",
                                                         "Data Area.svg",
                                                         "Data Bar Vertical.svg",
                                                         "Data Pie.svg",
                                                         "Data Trending (2).svg",
                                                         "Data Trending.svg",
                                                         "Data Usage.svg",
                                                         "Database.svg",
                                                         "Desktop Arrow Down.svg",
                                                         "Desktop Tower.svg",
                                                         "Dismiss Circle.svg",
                                                         "Document Bullet List Multiple.svg",
                                                         "Document Bullet List.svg",
                                                         "Document Key.svg",
                                                         "Document Lock.svg",
                                                         "Document Multiple.svg",
                                                         "Document One Page.svg",
                                                         "Document Text.svg",
                                                         "Document.svg",
                                                         "Edit.svg",
                                                         "Filmstrip Play.svg",
                                                         "Fingerprint.svg",
                                                         "Flag.svg",
                                                         "Folder Multiple.svg",
                                                         "Folder Open Vertical.svg",
                                                         "Folder Open.svg",
                                                         "Folder People.svg",
                                                         "Globe.svg",
                                                         "Hat Graduation.svg",
                                                         "Headset.svg",
                                                         "Heart Pulse.svg",
                                                         "Heart.svg",
                                                         "Image.svg",
                                                         "Key.svg",
                                                         "Laptop.svg",
                                                         "Layer Diagonal.svg",
                                                         "Lightbulb Checkmark.svg",
                                                         "Lightbulb.svg",
                                                         "Lock Closed.svg",
                                                         "Lock Shield.svg",
                                                         "Mail Alert.svg",
                                                         "Mail Attach.svg",
                                                         "Mail Error.svg",
                                                         "Mail Read.svg",
                                                         "Mail.svg",
                                                         "Map.svg",
                                                         "Megaphone Loud.svg",
                                                         "Merge.svg",
                                                         "Notebook.svg",
                                                         "Number Circle 1.svg",
                                                         "Number Circle 2.svg",
                                                         "Number Circle 3.svg",
                                                         "Number Circle 4.svg",
                                                         "Organization Horizontal.svg",
                                                         "Organization.svg",
                                                         "Panel Left Header Key.svg",
                                                         "Payment.svg",
                                                         "People Audience.svg",
                                                         "People Settings.svg",
                                                         "People Team.svg",
                                                         "People.svg",
                                                         "Person Accounts.svg",
                                                         "Person Desktop.svg",
                                                         "Person Settings.svg",
                                                         "Person Square.svg",
                                                         "Person Wrench.svg",
                                                         "Person.svg",
                                                         "Phone Desktop.svg",
                                                         "Phone Laptop.svg",
                                                         "Phone Tablet.svg",
                                                         "Phone Update.svg",
                                                         "Phone.svg",
                                                         "Presenter.svg",
                                                         "Question Circle.svg",
                                                         "Radar.svg",
                                                         "Receipt.svg",
                                                         "Ribbon Star.svg",
                                                         "Ribbon.svg",
                                                         "Road Cone.svg",
                                                         "Script.svg",
                                                         "Search.svg",
                                                         "Select All.svg",
                                                         "Settings Cog Multiple.svg",
                                                         "Settings.svg",
                                                         "Share Screen Person Overlay.svg",
                                                         "Share Screen Person.svg",
                                                         "Share.svg",
                                                         "Shield Error.svg",
                                                         "Shifts Activity.svg",
                                                         "Shopping Bag.svg",
                                                         "Signature.svg",
                                                         "Slide Layout.svg",
                                                         "Tablet Laptop.svg",
                                                         "Tablet.svg",
                                                         "Tap.svg",
                                                         "Task List Square.svg",
                                                         "Text First Line.svg",
                                                         "Text Number List.svg",
                                                         "Toolbox.svg",
                                                         "Top Speed.svg",
                                                         "Video.svg",
                                                         "Wallet Credit Card.svg",
                                                         "Window Edit.svg",
                                                         "Window.svg",
                                                         "Wrench.svg"
                                                     ]
                     },
    "SharePoint Teal":  [
                            "Organization_Dark.svg",
                            "Organization_Gray.svg",
                            "Organization_Light.svg"
                        ],
    "Planner Green":  [
                          "Calendar_Month_Dark.svg",
                          "Calendar_Month_Gray.svg",
                          "Calendar_Month_Light.svg",
                          "Checkmark_Circle_Dark.svg",
                          "Checkmark_Circle_Gray.svg",
                          "Checkmark_Circle_Light.svg",
                          "Checkmark_Dark.svg",
                          "Checkmark_Gray.svg",
                          "Checkmark_Light.svg",
                          "Clipboard_Dark.svg",
                          "Clipboard_Gray.svg",
                          "Clipboard_Light.svg",
                          "Clipboard_Task_List_Dark.svg",
                          "Clipboard_Task_List_Gray.svg",
                          "Clipboard_Task_List_Light.svg",
                          "Clock_Dark.svg",
                          "Clock_Gray.svg",
                          "Clock_Light.svg",
                          "Deploy.svg",
                          "Lightbulb_Dark.svg",
                          "Lightbulb_Gray.svg",
                          "Lightbulb_Light.svg",
                          "Organization_Dark.svg",
                          "Organization_Gray.svg",
                          "Organization_Light.svg",
                          "Ribbon_Planner_Dark.svg",
                          "Ribbon_Planner_Gray.svg",
                          "Ribbon_Planner_Light.svg",
                          "Tap_Dark.svg",
                          "Tap_Gray.svg",
                          "Tap_Light.svg",
                          "Task_List_LTR_Dark.svg",
                          "Task_List_LTR_Gray.svg",
                          "Task_List_LTR_Light.svg",
                          "Task_List_Square_Dark.svg",
                          "Task_List_Square_Gray.svg",
                          "Task_List_Square_Light.svg",
                          "Window Edit.svg"
                      ],
    "Microsoft Purple":  [
                             "Building_Gray.svg",
                             "Settings_Dark.svg",
                             "Settings_Gray.svg",
                             "Settings_Light.svg",
                             "Tap_Dark.svg",
                             "Tap_Gray.svg",
                             "Tap_Light.svg"
                         ]
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { ICONS_MAP };
} else {
    window.ICONS_MAP = ICONS_MAP;
}
